# ===================================================================
# DEV PROFILE
# Kích hoạt: --spring.profiles.active=dev
# ===================================================================

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/pets_platform_dev
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-dev.sql
      data-locations: classpath:db/data-dev.sql
      continue-on-error: true

logging:
  level:
    root: INFO
    com.petsplatform: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.jdbc.core: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
